services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1234"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    command: 
      - /opt/mssql/bin/sqlservr